# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_listener: true
    body_converter:
        enabled: true    
        validate: true
        validation_errors_argument: validationErrors # This is the default value        
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            #- { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
            - { path: '^/', stop: true }
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true    
    routing_loader:
        default_format: json                        
    # exception:
    #         codes:
    #             'Symfony\Component\HttpKernel\Exception\NotFoundHttpException': 404
    #             'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
    #         messages:
    #             'Symfony\Component\Routing\Exception\ResourceNotFoundException': true        
    #                                                     # will eventually be JSON formated
            # exception_controller: 'fos_rest.exception.controller:showAction'
            # codes:
            #     Doctrine\ORM\EntityNotFoundException: 404