# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Osedax' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Osedax
    pod 'Swinject', '~> 2.6.2'
    pod 'SwinjectAutoregistration'
    pod 'SwinjectStoryboard'
    pod 'Heimdallr', :git => 'https://github.com/fbeeper/Heimdallr.swift', :tag => '3.7.0'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    pod 'RealmSwift'
    pod 'Google-Mobile-Ads-SDK'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
        end
    end
end
